//
//  main.c
//  energy_sort
//
//  Created by Ivan Chernyshev on 4/1/20.
//  Copyright © 2020 Ivan Chernyshev. All rights reserved.
//

// This program takes data created by energy_calculator and sorts it
// Outputs a file with a table of energies and
// Precondition: the file must have been generated by energy_calculator and have the naming convention energy_levels_npi_<number of pions>_pmax_<maximum momentum coordinate magnitude>.txt
#include <string.h>
#include <stdlib.h>
#include <stdio.h>

int main(int argc, const char * argv[]) {
    const double energy_accuracy = 10000.; // The number that an index in the array would be divided by to get to the energies
    //const int n_pi_index = 18; // The index of the number of pions, in any filename required by the naming convention in the precondition
    
    // This program takes in the file name as a command line argument
    if(argc != 4)
    {
        printf("%s\n", "Error: the command-line argument must be the following: target file, minimum energy, maximum energy (latter two are to a precision of up to 4 decimal places, all others are truncated). Exiting now.");
        exit(EXIT_FAILURE);
    }
    
    // Get the file name, number of pions and the maximum momentum coordinate from the command line argument
    char filename[80]; // Index is chosen so that file names under the convention in the precondition have enough space to store any file name with n_pi and pmax up to 3 digits (if you need any more than that, you'd better wait a century or so until a computer with enough storage is invented), and in addition the word "_sorted_emin_<minimum energy>_emax_<maxiumum energy>"
    strcpy(filename, argv[1]);
    FILE* fptr_pion_r;
    fptr_pion_r = fopen(argv[1], "r");
    char* file_specs;
    file_specs = strtok(filename, "_");
    file_specs = strtok(NULL, "_");
    file_specs = strtok(NULL, "_");
    file_specs = strtok(NULL, "_");
    int n_pi = atoi(file_specs);
    
    // Repair the damage done to filename by strtok
    filename[strlen(filename)] = '_';
    filename[strlen(filename)] = '_';
    filename[strlen(filename)] = '_';
    filename[strlen(filename)] = '_';

    // use fgets to read off the header
    char header_read[26*n_pi+27];
    fgets(header_read, 26*n_pi+26, fptr_pion_r);
    
    // Now, obtain the minimum and maximum energy from the command line
    double min_erg = atof(argv[2]);
    double max_erg = atof(argv[3]);
    
    // Now, create the file to read to
    char* read_to_file = strtok(filename,".");
    char readfile_appendage[42];
    sprintf(readfile_appendage, "_sorted_emin_%4.4f_emax_%4.4f.txt", min_erg, max_erg);
    strcat(read_to_file, readfile_appendage);
    strtok(read_to_file, ".");
    strtok(NULL, ".");
    read_to_file[strlen(read_to_file)] = '_';
    read_to_file[strlen(read_to_file)] = '_';
    FILE* fptr_pion_w;
    fptr_pion_w = fopen(read_to_file, "w");
    printf("File %s created.\n", read_to_file);
    
    // Now, translate minimum and maximum energy into a language understandable by a matrix and indices, and create the array
    long int index_adjuster = (long int) (min_erg*energy_accuracy); // The number that must be added to an index before it can be divided by energy_accuracy to get the energy
    long int num_of_energies = (long int) (max_erg*energy_accuracy - index_adjuster);
    long int sort_arr[++num_of_energies];
    for(int i = 0; i < num_of_energies; i++)
        sort_arr[i] = 0;
    
    // Now read off the lines in the target file, and do the sort by incrementing the array elements corresponding to the
    char lineread[12*n_pi+23];
    char* energyread;
    double current_E;
    long int E_index;
    while(fgets(lineread, 12*n_pi+23, fptr_pion_r) != NULL)
    {
        energyread = strtok(lineread, "|");
        current_E = atof(energyread);
        if (current_E >= min_erg && current_E <= max_erg)
        {
            long int unconverted_accuracy = current_E*energy_accuracy - index_adjuster;
            E_index = current_E*energy_accuracy;
            E_index -= index_adjuster;
            sort_arr[E_index]++;
            
            if(sort_arr[E_index] < 0)
                printf("%s%4.4f%s\n", "WARNING: too many data under energy ", current_E, ", long int range overflow.");
        }
    }
    
    // Now, use the array to fill out the write-to file
    fprintf(fptr_pion_w, "%s\n", "Energy : Num of elements");
    for(int i = 0; i < num_of_energies; i++)
    {
        if(sort_arr[i] != 0)
            fprintf(fptr_pion_w, "%4.4f:%li\n",(i + index_adjuster)/energy_accuracy, sort_arr[i]);
    }
    
    fclose(fptr_pion_r);
    fclose(fptr_pion_w);
    
    return 0;
}
