# Generated by Django 3.0.6 on 2020-11-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ff_fit', '0002_auto_20201126_0705'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ff_fit',
            name='unique_fit',
        ),
        migrations.RemoveField(
            model_name='ff_fit',
            name='A3_over_V4',
        ),
        migrations.RemoveField(
            model_name='ff_fit',
            name='A3_over_V4_err',
        ),
        migrations.RemoveField(
            model_name='ff_fit',
            name='chained',
        ),
        migrations.AddField(
            model_name='ff_fit',
            name='fit_type',
            field=models.TextField(default='separate', help_text='separate or continue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ff_fit',
            name='pt3_tau_dict',
            field=models.TextField(help_text='Use gv.dump to package tau dict of 3pt, and turn into hexcode', null=True),
        ),
        migrations.AddConstraint(
            model_name='ff_fit',
            constraint=models.UniqueConstraint(fields=('data_file_name', 'fit_type', 'include_2pt', 'include_3pt', 'include_sum', 'data_and_results', 'prior_hexcode', 'pt2_nstates', 'pt2_tmin', 'pt2_tmax', 'pt3_nstates', 'pt3_A3_tsep_min', 'pt3_A3_tsep_max', 'pt3_V4_tsep_min', 'pt3_V4_tsep_max', 'sum_nstates', 'pt3_tau_dict', 'sum_A3_tsep_min', 'sum_A3_tsep_max', 'sum_V4_tsep_min', 'sum_V4_tsep_max', 'sum_tau_cut', 'id_num'), name='unique_fit'),
        ),
    ]
